### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by efurtado26** [catcamacho/emocodes#1]
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/0g/g8tyy3vn2zxcv2_bfxpbpr780000gn/T/ipykernel_6983/3530147867.py in <module>
      3 
      4 con = ec.Consensus()
----> 5 con.interrater_consensus([dm_emily, dm_cat], ['Emily','Cat'])
      6 con.consensus_scores.to_csv('DM_consensus_scores.csv')
      7 con.mismatch_segments.to_csv('DM_mismatched_segments.csv')

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/emocodes/analysis/codes.py in interrater_consensus(self, codes_list, rater_list)
    174 
    175         self.raters = rater_list
--> 176         self.consensus_scores = compute_exact_match(self.codes_list, self.raters, reference=None)
    177 
    178         r = range(0, len(self.raters))

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/emocodes/analysis/codes.py in compute_exact_match(ratings_list, raters_list, reference)
    343                 exact_match_stats.loc['{0}_{1}'.format(i, h), 'RatingsB'] = raters_list[a[1]]
    344                 exact_match_stats.loc['{0}_{1}'.format(i, h), 'ColumnVariable'] = b
--> 345                 exact_match_stats.loc['{0}_{1}'.format(i, h), 'PercentOverlap'] = (df1[b] == df2[b]).mean() * 100
    346     return exact_match_stats
    347 

TypeError: string indices must be integers`

**Comment by catcamacho** [comment]
This is an issue the documentation, not the code. You need to import the dataframes before passing to interrater_consensus. Will update with next release.
