### ISSUE TITLE
Error with emocodes attributes

### ISSUE THREAD

**Issue by sofiaws** [catcamacho/emocodes#2]
I installed the EmoCodes python library, but ran into some errors. 

When I run ‘features = ec.ExtractVideoFeatures().extract_features(video_file, sampling_rate)’ or ‘features_df = ec.ExtractVideoFeatures().extract_features(video_file, sampling_rate, outfile)’ (the examples given on GitHub and readthedocs, respectively), I get an error saying that ExtractVideoFeatures is not an attribute from emocodes. 

In fact, when I run ‘dir(ec)’, I get a list with very few attributes (see below). I’m able to use the functions mentioned in this list (e.g., get_video_length() and compute_luminance()). 

Do you have any idea of what might be occurring or how can I install all the attributes?

Thank you very much for your help and for the effort of developing a standardized coding system for socioemotional content in video stimuli, it's an incredible contribution to the field!

dir(ec)
Out[12]: 
['CodeTimeSeries',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'code',
 'compute_luminance',
 'get_code_labels',
 'get_video_length',
 'save_timeseries',
 'validate_convert_timestamps',
 'video']

**Comment by catcamacho** [comment]
Hmm, I tried reproducing the error (installed latest version using pip and ran the example code) and it is working just fine on my end. Could you give me some more information about 1) your operating system, 2) how you installed the library and 3) the full code you used that produced this error?

Hopefully we can figure out what's going on!

**Comment by sofiaws** [comment]
Thank you for your quick reply!

I use Linux Ubuntu 22.04.1 LTS.
I created a new python environment (version 3.10.6) and installed EmoCodes using 'pip3 install emocodes --user'.

Here is **the code** I used:
import emocodes as ec

help(ec)
dir(ec)

video_file = 'xxxxx' # must be MP4

sampling_rate = 10 # in Hz

video_duration = ec.get_video_length(video_file) #get_video_length is mentioned on dir(ec)
print(video_duration) #it works

features = ec.ExtractVideoFeatures().extract_features(video_file, sampling_rate) #code mentioned on the documentation, does not work

features_v2 = ec.compute_luminance(video_file, sampling_rate, video_duration) #compute_luminance is mentioned on dir(ec)
print(features_v2) #it works



And here is the **console output**:
import emocodes as ec

help(ec)
Help on package emocodes:

NAME
    emocodes

PACKAGE CONTENTS
    code
    graphing
    video

FILE
    /home/xxxx/.local/lib/python3.10/site-packages/emocodes/__init__.py



dir(ec)
Out[3]: 
['CodeTimeSeries',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'code',
 'compute_luminance',
 'get_code_labels',
 'get_video_length',
 'save_timeseries',
 'validate_convert_timestamps',
 'video']

video_file = '/run/user/1001/gvfs/smb-share:server=jcfiler.uzh.ch,share=mri_group_raschle/1_General/3_Projects/1_SMILIES_Project/Movie paradigm/Version SHORT_100.mp4' # must be MP4

sampling_rate = 10 # in Hz

video_duration = ec.get_video_length(video_file) #get_video_length is mentioned on dir(ec)

print(video_duration) #it works
748620

features = ec.ExtractVideoFeatures().extract_features(video_file, sampling_rate) #code mentioned on the documentation, does not work
Traceback (most recent call last):

  File "/tmp/ipykernel_8972/759085822.py", line 1, in <module>
    features = ec.ExtractVideoFeatures().extract_features(video_file, sampling_rate) #code mentioned on the documentation, does not work

AttributeError: module 'emocodes' has no attribute 'ExtractVideoFeatures'


features_v2 = ec.compute_luminance(video_file, sampling_rate, video_duration) #compute_luminance is mentioned on dir(ec)

print(features_v2) #it works
                         luminance         R         G         B
time                                                            
1970-01-01 00:00:00.000   0.000003  0.000003  0.000003  0.000003
1970-01-01 00:00:00.100   0.000000  0.000000  0.000000  0.000000
1970-01-01 00:00:00.200   0.000000  0.000000  0.000000  0.000000
1970-01-01 00:00:00.300   0.000000  0.000000  0.000000  0.000000
1970-01-01 00:00:00.400   0.000000  0.000000  0.000000  0.000000
                           ...       ...       ...       ...
1970-01-01 00:12:28.100   1.448586  3.463772  0.464584  1.229888
1970-01-01 00:12:28.200   1.461870  3.607030  0.611121  0.216142
1970-01-01 00:12:28.300   0.935921  2.999988  0.000328  0.339751
1970-01-01 00:12:28.400   0.969275  2.333283  0.333071  0.667641
1970-01-01 00:12:28.500   0.000000  0.000000  0.000000  0.000000

[7486 rows x 4 columns]

**Comment by sofiaws** [comment]
I thought that perhaps the problem is occuring because of some dependency. So here is a list of all packages installed in the environment (got with 'pip list'):
pip list
Package                       Version
----------------------------- -----------
alabaster                     0.7.12
arrow                         1.2.3
astroid                       2.11.7
atomicwrites                  1.4.0
attrs                         21.4.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
beautifulsoup4                4.11.1
binaryornot                   0.4.4
black                         22.6.0
bleach                        4.1.0
brotlipy                      0.7.0
certifi                       2022.9.24
cffi                          1.15.1
chardet                       4.0.0
charset-normalizer            2.0.4
click                         8.0.4
cloudpickle                   2.0.0
colorama                      0.4.5
contourpy                     1.0.6
cookiecutter                  1.7.3
cryptography                  38.0.1
cycler                        0.11.0
debugpy                       1.5.1
decorator                     4.4.2
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.4
docutils                      0.18.1
emocodes                      0.1.0
entrypoints                   0.4
et-xmlfile                    1.1.0
fastjsonschema                2.16.2
flake8                        4.0.1
fonttools                     4.38.0
idna                          3.4
imageio                       2.22.4
imageio-ffmpeg                0.4.7
imagesize                     1.4.1
importlib-metadata            4.11.3
inflection                    0.5.1
intervaltree                  3.1.0
ipykernel                     6.15.2
ipython                       7.31.1
ipython-genutils              0.2.0
isort                         5.9.3
jedi                          0.18.1
jeepney                       0.7.1
jellyfish                     0.9.0
Jinja2                        3.1.2
jinja2-time                   0.2.0
jsonschema                    4.16.0
jupyter_client                7.3.5
jupyter_core                  4.11.1
jupyterlab-pygments           0.1.2
keyring                       23.4.0
kiwisolver                    1.4.4
lazy-object-proxy             1.6.0
MarkupSafe                    2.1.1
matplotlib                    3.6.2
matplotlib-inline             0.1.6
mccabe                        0.7.0
mistune                       0.8.4
moviepy                       1.0.3
mypy-extensions               0.4.3
nbclient                      0.5.13
nbconvert                     6.4.4
nbformat                      5.5.0
nest-asyncio                  1.5.5
numpy                         1.23.4
numpydoc                      1.4.0
opencv-python                 4.6.0.66
openpyxl                      3.0.10
packaging                     21.3
pandas                        1.5.1
pandocfilters                 1.5.0
parso                         0.8.3
pathspec                      0.9.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.3.0
pip                           22.2.2
platformdirs                  2.5.2
pluggy                        1.0.0
ply                           3.11
poyo                          0.5.0
proglog                       0.1.10
prompt-toolkit                3.0.20
psutil                        5.9.0
ptyprocess                    0.7.0
pycodestyle                   2.8.0
pycparser                     2.21
pydocstyle                    6.1.1
pyflakes                      2.4.0
Pygments                      2.11.2
pylint                        2.14.5
pyls-spyder                   0.4.0
pyOpenSSL                     22.0.0
pyparsing                     3.0.9
PyQt5-sip                     12.11.0
pyrsistent                    0.18.0
PySocks                       1.7.1
python-dateutil               2.8.2
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.5.0
python-slugify                5.0.2
pytz                          2022.1
pyxdg                         0.27
PyYAML                        6.0
pyzmq                         23.2.0
QDarkStyle                    3.0.2
qstylizer                     0.1.10
QtAwesome                     1.0.3
qtconsole                     5.3.2
QtPy                          2.2.0
requests                      2.28.1
rope                          0.22.0
Rtree                         0.9.7
SecretStorage                 3.3.1
setuptools                    65.5.0
sip                           6.6.2
six                           1.16.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.3.2.post1
Sphinx                        5.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.3.3
spyder-kernels                2.3.3
testpath                      0.6.0
text-unidecode                1.3
textdistance                  4.2.1
three-merge                   0.1.1
tinycss                       0.4
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.1
tornado                       6.2
tqdm                          4.64.1
traitlets                     5.1.1
typing_extensions             4.3.0
ujson                         5.4.0
Unidecode                     1.2.0
urllib3                       1.26.12
watchdog                      2.1.6
wcwidth                       0.2.5
webencodings                  0.5.1
whatthepatch                  1.0.2
wheel                         0.37.1
wrapt                         1.14.1
wurlitzer                     3.0.2
yapf                          0.31.0
zipp                          3.8.0

**Comment by sofiaws** [comment]
I use Linux Ubuntu 22.04.1 LTS and python release 3.10.6.

I found out what the issue was! 
Emocodes requires python-magic-bin==0.4.14, but according to [this thread ](https://stackoverflow.com/questions/66732553/meeting-a-pip-requirement-using-an-alternative-module), it is not available on Linux (or something like that) and you need to install it from GitHub. So, I created a new environment and installed both python-magic-bin and emocodes from GitHub. Now I can see all attributes :) 

Here is the code I used:
pip install git+https://github.com/julian-r/python-magic.git
pip install pip install git+https://github.com/catcamacho/emocodes.git

I look forward to using emocodes!
Thank you

**Comment by catcamacho** [comment]
Oh good! I'll add those instructions to the docs so other folks using linux can get python-magin-bin installed.  Thanks for posting the solution you found!
